import { type NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import ChatBox from "../components/ChatBox/ChatBox";

const Home: NextPage = () => {
  const messages = ["Hello", "World, this is a test", "Hi", "Hello", "World, this is a test ", "Hi", "Hello", "World, this is a test", "Hi", "Hello", "World, this is a test", "Hi"]
  return (
    <>
      <Head>
        <title>Cloud</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Navbar />
        <div className="min-w-full flex flex-row justify-evenly items-center gap-2 p-4 mt-24">
          <ChatBox messages={messages} />
          <ChatBox messages={messages} />
        </div>
      </main>
    </>
  );
};

export default Home;

